---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: checkmydumps.checkmydump.com
  namespace: checkmydump
spec:
  scope: Namespaced
  group: checkmydump.com
  names:
    kind: CheckMyDump
    plural: checkmydumps
    singular: checkmudump
    # shortNames:
    #   - ckp
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              # x-kubernetes-preserve-unknown-fields: true
              properties:
                schedule:
                  type: string
                  description: Cron format (e.g., "0 1 * * *"), in UTC
                size:
                  type: string
                  description: The database size for the volume
                sourceClusterName:
                  type: string
                  description: The original cluster name from the backup
                secretName:
                  type: string
                  description: |
                    The secret with the credentials to access the backup bucket
                    (ACCESS_KEY_ID and SECRET_ACCESS_KEY)
                destinationPath:
                  type: string
                  description: |
                    The path in the bucket where the backup is stored.
                    It's the same used in cloudnative pg
                endpointURL:
                  type: string
                  description: |
                    The endpoint url of the s3 service
                    It's the same used in cloudnative pg
                checkQueries:
                  type: array
                  items:
                    type: string
                  description: |
                    The endpoint url of the s3 service
                    It's the same used in cloudnative pg
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: checkmydumpqueries.checkmydump.com
  namespace: checkmydump
spec:
  scope: Namespaced
  group: checkmydump.com
  names:
    kind: CheckMyDumpQuery
    plural: checkmydumpqueries
    singular: checkmydumpquery
    # shortNames:
    #   - ckpq
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              # x-kubernetes-preserve-unknown-fields: true
              required: ["query"]
              properties:
                query:
                  type: string
                  description: "The SQL query to execute"
                expectedResult:
                  type: string
                  description: "The expected result (stringified)"
                notification:
                  type: string
                  description: "Where notify if result not match"
                store:
                  type: boolean
                  description: "Decide if store the logs (default false)"
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
