---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: checkmydump
  name: checkmydump-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: checkmydump
  name: checkmydump-role-namespaced
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [checkmydump.com]
    resources: [checkmydumps, checkmydumpqueries]
    verbs: [list, watch, patch]

  # Application: other resources it produces and manipulates.
  - apiGroups: [""]
    resources: [pods, pods/exec]
    verbs: [get, create, delete]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get]
  - apiGroups: ["postgresql.cnpg.io"]
    resources: [clusters]
    verbs: [get, create, delete]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, create, delete]
  - apiGroups: ["barmancloud.cnpg.io"]
    resources: [objectstores]
    verbs: [get, create, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkmydump-role-cluster
  namespace: checkmydump
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups:
      - admissionregistration.k8s.io/v1
      - admissionregistration.k8s.io/v1beta1
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [checkmydump.com]
    resources: [checkmydumps, checkmydumpqueries]
    verbs: [list, watch]

  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get, create, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: checkmydump-rolebinding-cluster
  namespace: checkmydump
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: checkmydump-role-cluster
subjects:
  - kind: ServiceAccount
    name: checkmydump-account
    namespace: checkmydump
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: checkmydump
  name: checkmydump-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: checkmydump-role-namespaced
subjects:
  - kind: ServiceAccount
    name: checkmydump-account
